apiVersion: v1
kind: ConfigMap
metadata:
  name: service-point
data:
  url: 'replace_me'
  url-external: 'replace_me'
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: database-host
data:
  url: xraylabdb
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: buckets-config
data:
  bucket-source: 'replace_me'
  bucket-base-name: 'replace_me'